[package]
name = "sponge"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
getrandom = { version = "0.2.3", features = ["js"] }
rand = "0.8.4"
svg = "0.10.0"
wasm-bindgen = "0.2"
